cluster-configs:
    secrets:
        jenkins:
            clientId: 5e5c1883cbcfc415c745
            clientSecret: 47ff421fed26a006ab256bf9cdee0e9c089c42cf
            gitReadSshPrivateKey: |-
                -----BEGIN OPENSSH PRIVATE KEY-----
                b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
                NhAAAAAwEAAQAAAgEAoZ0l8L3f/trukcvQCe8oWVa2/C7MzjUQyn2k/Zvv2O+GSm32B7a1
                O4pwVFIPQrhBG1S12HBI7BYFMlSklAw1IKJ/V2GY1fPrOhMqi/l5n3HPdcKu7RrfRv4mj1
                p0zydMmWRebW9odNmv2SYkWrwvAvfOWfC+ltW+Lx3uFv1ADcuIpv6DV7FQRbQJ7mKOVSGd
                diiUjy3glYLPSwouyfg9sXewp+O8Ayn6V4DFvh6zQVRXuHDBUvbmvt6NBPFagjD/ZHU+Fo
                2iMV2TpnUq18xhytb8q96inIy8b+ZspV9yoBlnJzvOySUnfZqPMOnRwsrWywpIGlenI3Aa
                Sd1WnjlwpO5xwlP1adXcLa9tik6m0SrvIu7i0NGO9sus5xpEuV+lz3m/Kvwx048Ewj5VIb
                7gTaDkGNh+3VdTJfeALx+pC0rknBKgbHE03bmMcOPZZ5uD+KePfvrbl5Omz5fLUSD23fBZ
                szfxm3rVZ41OTXNf88Ph426llUUJc4uJG0KVhZdk81F+iPFiqsqH/QqGq7iqN0ao21FCkK
                LkcdmLxE7dC0MXTCw25DNFhvQW367SHRbaf/RvZM+lLExI/79wGJXTq7B/OvrsDFdU1BAr
                D7dJmm5lfTn5tXQbV3QdKNA4mNKOr8UraLmmZUnHksJsCaJkoKLQnkPPM8QNOOGbf+xPgs
                8AAAdQa1eMwmtXjMIAAAAHc3NoLXJzYQAAAgEAoZ0l8L3f/trukcvQCe8oWVa2/C7MzjUQ
                yn2k/Zvv2O+GSm32B7a1O4pwVFIPQrhBG1S12HBI7BYFMlSklAw1IKJ/V2GY1fPrOhMqi/
                l5n3HPdcKu7RrfRv4mj1p0zydMmWRebW9odNmv2SYkWrwvAvfOWfC+ltW+Lx3uFv1ADcuI
                pv6DV7FQRbQJ7mKOVSGddiiUjy3glYLPSwouyfg9sXewp+O8Ayn6V4DFvh6zQVRXuHDBUv
                bmvt6NBPFagjD/ZHU+Fo2iMV2TpnUq18xhytb8q96inIy8b+ZspV9yoBlnJzvOySUnfZqP
                MOnRwsrWywpIGlenI3AaSd1WnjlwpO5xwlP1adXcLa9tik6m0SrvIu7i0NGO9sus5xpEuV
                +lz3m/Kvwx048Ewj5VIb7gTaDkGNh+3VdTJfeALx+pC0rknBKgbHE03bmMcOPZZ5uD+KeP
                fvrbl5Omz5fLUSD23fBZszfxm3rVZ41OTXNf88Ph426llUUJc4uJG0KVhZdk81F+iPFiqs
                qH/QqGq7iqN0ao21FCkKLkcdmLxE7dC0MXTCw25DNFhvQW367SHRbaf/RvZM+lLExI/79w
                GJXTq7B/OvrsDFdU1BArD7dJmm5lfTn5tXQbV3QdKNA4mNKOr8UraLmmZUnHksJsCaJkoK
                LQnkPPM8QNOOGbf+xPgs8AAAADAQABAAACAAM8iC5G3Hy6cZoHYjkALHQd00biDbaFcsvd
                +nk+osM4syW79pow4HaUjPx190ze2fHdRbgxhzCWnglKbT9Q0Hf0NNqRFvMm/LYdhUb4ZU
                /Tvq1WvqSDydE4G4hxupjqe1NiqxMqbrBiO8Nz/h9ipflurMsO51Ta8/Bcv5RueqNFr2qW
                2EmkL32lUrl1KzVkoiyoJ5X/HdXj3H93ggl/d1LzEG5t4w/T9XrVUj5PrSVgaVKBJbCh8X
                zzo+50pFtEfqlbY5N7+xgZQSQAvJyKDcOykPEAlOFHGjufk+zRFzbs1OhvzCVc3QQGv9oU
                nKO8CMJHCERIpjgNKQgDUQVQevZ69WqEp/IfXTeoa0ZjIUqZ36vVAV1sMSfLUC85jU9XY9
                d4cBaIQBottG3eXuukslyRepY127RnFnzEp60Oi0CLBNbKCvW+j4NzIpFjpvGYi1F8sA8h
                vvGDStVYjUzdCIMCnuYaeb8qBFa877xWj0ay7UhI3IridfWCBFBt1LY2Mg2rfu6surR5gr
                6EIHX148Z/HpaFKRaMdGW4k30hZ9JWWLhlWboNiwMxlh4x2f6B5ltpTtWt7SEnFDy3k+tk
                d1/YyPIbTqnv0/88xXOB09+pBBkZiD2SglqzJi7ourcy2pWLtbHgJ1F1E7N/x0uKHLeGgc
                rMnKMQcUu598l/Hl7RAAABAE+l3UoUIH7YQ6dgCKEEdr+pg0/3xlx+Tzx3bz15KgWT1lbw
                gY0WQIOhHUhF4YftKI/JICMnfodatuLOVpidurbsG36rTMTWNtj2n+7l7c8BDOoYi3Myau
                X3mMt1rwdci5HDUd77SFuWeEvhX+sydQ1HCXQk1AD4YHuNgU+wTiQPV12d2MUny/nIXP7I
                T2gy5nwW+OXFeo6M2pysIB8oPUXRboQXp+4M7EpW3tX8jJASqwpkIv7TpqM6bB5EaS1yC6
                +D5reqmJ7HiTrS4k2oqJogwgx3RYPgtPKUYVyjnrtr6D/O6dURIeJcI9utIBG5Nj07F84q
                fETTecWgkm0I99sAAAEBAL5laeZFSzh9tRRqaohbawmGEN9thqVRB8m5glKEjp9yPbTpq8
                FS+WgyJ0jZX/gKl9HB3jhrtRWkCJKwIYw/AvCSwjbX61puLA9mJwdbWxWsJ+TXdUIaPpMr
                0u0fIHeb94l+cCnpUZcM/zMhTG23AWqOYya8qkRvNRadMJfw+QheFH5IXgwzsCzlY9rLYj
                whBTSuq8fld0aWo5X/YNlfSz1Z0zcmeNb+bIt57YBai89W4wrTO4ZnCVfwgARyB0ZKqLXB
                mnWginEyL5HBn+8nqwKPIKkDinWnt22vyxFe6HqS0j0m49rprq48oH0rw65DtzqLlSeEUn
                aQcuPQXtdtUBEAAAEBANlM41JFGIBAjS74Tb+pBT7olcSOgVZEoh8+/ZTLe0vq/wf2HCVw
                oevz63jgVRSuabWTsjF7FBoig09BuUf1K3FcCbWtzAADwGHMnadzJhqNV8jmU+utNng/7d
                oHs5qHb6hNku3qhzJqnP12rPkEdnX22mA8Fog0Wh7e8WF5qR0bZ1ll0cFDrigaUcgTdkgE
                +arGfoTX3dIXFx9+TC07UxvG4q8lBExG2v05ogZ7gK5eTYFDxtQkNgQ0szxXSUaEWox4O9
                QBpL6LiB59xbjECXNPR/tWjtjiiHYj1MYOX/q8mGQgKwRibPEaY8xHC3RXhUDsUnvewFk0
                hGM6LQfuhN8AAAAWZmFpemFuZW5hdG9yQGdtYWlsLmNvbQECAwQF
                -----END OPENSSH PRIVATE KEY-----
            gitReadAccessToken: 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
            dockerConfigJson: |-
                {
                  "auths": {
                    "https://index.docker.io/v1/": {
                      "username": "tattvafoundation",
                      "password": "Tattva@2022",
                      "email": "support@tattvafoundation.org",
                      "auth": "dGF0dHZhZm91bmRhdGlvbjpUYXR0dmFAMjAyMg=="
                    }
                  }
                }
            dockerUsername: tattvafoundation
            dockerPassword: Tattva@2022
            kubeConfigs:
                uat:
                    apiVersion: v1
                    clusters:
                        - cluster:
                            server: https://69536F8F86E63BBDCBDF5690C3B09461.gr7.ap-south-1.eks.amazonaws.com
                            certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJME1ERXlOREV3TWpVeU1sb1hEVE0wTURFeU1URXdNalV5TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSnhqCkg1N3hwbmdzTzE1V0tFM084K0ZEci9zZXBEOTJxSGZBSlhTdEdZQ1pYaVBGS2JZQnNEQVBoVjQxT0ZZM21MTE8KeklZQXhoOG5hTjNEbitkVFJQakRnQmk1UEhwTEtIUTRucjBaQnlrbTRNL0hNdHZMV1M1SmRVdCtzM0t2NXZPNwptaUkyVS9MQ0NsUkRJODZaMlFVTWlneHd3bzRMK1kzQVkyRmdMSExYT0tsZCtxb29RQXFad2dKK05UcFZMYTA3CkNwUWZzaTl4QmNWbEMxc2F2S2pZNURnZW5KZ0luVFFIZUhlQ2FVTTdXdXFhUXFUVjl4cTgxU1dYNzYyaVExU0wKTGo5K2xDdFRRKzczemVzN0ZFYy9qZFN1QVd6WHVabG5GeFV0MEV3Mit5TGNueldHZlBObVhxY2E1cnYxWU9pcAo3NzRFK0dYUHJ5RlA2c2xvKytNQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZPMjBSV2ZzUVNkZmh5S3Z5V2I0ZWovWnppdnhNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSXZFTFFTWnNPRFhMQnViZTVwcQpOcjlOMGtWTGdxL2lqbTJtQXhQTFQ1YkVIZW5paWFraFF3Y3VydDlZS3JHV1ozNEI5Ull1bEh2MlJhWHNXTDRVCkMvTzRacHBZdDNCRGdXRUh6SlZ4TjhBTElXV1RKOFhHak9kZ2NiVzZPNnVOY0I2YndIdEpsR0UwN2c4SVJwSlcKUFNqc3hEL28vdFdUSW1MRG5EbzhpOU9LK2lNUlVRYkF5UkJSVEJJN1lZbk1Oem45ZGhVT0g5c3k2ZWRjdkZCQQpCcEo1a0xmaS85bEgwM1BXNVZ3Y0RtRmpNMGRkMGR6azNFUEdyMHlkNEhrZlA4a3E4bVZHQnArcURuZmJQUC9zCmFwS1JZa1A5aEFMSkU1Z3dzeDl2eXIzZDEyK1BZRDhRT0pUSmovOVR1aUNWdjFpWVIvN1BZYWxBaytEWmxOcWgKSXhZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
                          name: demo
                    contexts:
                        - context:
                            cluster: eks-demo
                            namespace: jenkins
                            user: eks-demo
                          name: eks-demo
                    current-context: eks-demo
                    users:
                        - name: eks-demo
                          user:
                            exec:
                                apiVersion: client.authentication.k8s.io/v1alpha1
                                args:
                                    - token
                                    - -i
                                    - demo
                                command: aws-iam-authenticator
                                env:
                                    - name: AWS_ACCESS_KEY
                                      value: AKIA2MJ33GKMOXQS2P4B
                                    - name: AWS_SECRET_ACCESS_KEY
                                      value: 6viKg5B0+/c/npro95o7FUK/dyAiirEc6IP1ZTev
                                    - name: AWS_REGION
                                      value: ap-south-1
